// src/react/react-dealership-app/src/components/CarItem.jsx
import React from 'react';

function CarItem({ cars, onEditCar, onViewCarDetails, onDeleteCar }) {
  return (
    <div>
      {cars.map(car => (
        <div key={car.id} className="car-item">
          <div className="car-info">
            <div className="car-title">{car.year} {car.make} {car.model}</div>
          </div>
          <div className="car-actions">
            <button className="btn-small" onClick={() => onViewCarDetails(car)}>
              details
            </button>
            <button className="btn-small" onClick={() => onEditCar(car)}>
              ✏️
            </button>
            <button 
              className="btn-small delete-btn" 
              onClick={() => onDeleteCar(car.id)}
            >
              🗑️
            </button>
          </div>
        </div>
      ))}
    </div>
  );
}

export default CarItem;

// src/vuejs/src/components/CarItem.vue
<script setup>
defineProps({
  cars: Array
})

defineEmits(['edit-car', 'view-car-details', 'delete-car'])
</script>

<template>
  <div v-for="car in cars" :key="car.id" class="car-item">
    <div class="car-info">
      <div class="car-title">{{ car.year }} {{ car.make }} {{ car.model }}</div>
    </div>
    <div class="car-actions">
      <button class="btn-small" @click="$emit('view-car-details', car)">details</button>
      <button class="btn-small" @click="$emit('edit-car', car)">✏️</button>
      <button class="btn-small delete-btn" @click="$emit('delete-car', car.id)">🗑️</button>
    </div>
  </div>
</template>
